const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.bound,
		C3.Behaviors.EightDir,
		C3.Behaviors.Platform,
		C3.Plugins.TiledBg,
		C3.Behaviors.custom,
		C3.Behaviors.Bullet,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Plugins.Mouse,
		C3.Behaviors.Fade,
		C3.Behaviors.Sin,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.custom.Acts.SetSpeed,
		C3.Behaviors.custom.Acts.AccelerateAngle,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.TiledBg.Acts.SetPos,
		C3.Plugins.System.Cnds.Every,
		C3.Behaviors.custom.Acts.Reverse,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Behaviors.Bullet.Acts.SetAcceleration,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Mouse.Acts.SetCursor,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Mouse.Acts.SetCursorSprite,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Behaviors.custom.Acts.SetAngleOfMotion
	];
};
self.C3_JsPropNameTable = [
	{Solid: 0},
	{BoundToLayout: 0},
	{"8Direction": 0},
	{Hand1: 0},
	{Platform: 0},
	{Hand2: 0},
	{Custom: 0},
	{gamBg: 0},
	{Bullet: 0},
	{Ball: 0},
	{GameOver: 0},
	{Keyboard: 0},
	{Solids: 0},
	{Text: 0},
	{Text2: 0},
	{Text3: 0},
	{Sprite: 0},
	{Text4: 0},
	{SCORET: 0},
	{rtyBg: 0},
	{Sprite2: 0},
	{retry: 0},
	{Mouse: 0},
	{Fade: 0},
	{FadeIn: 0},
	{FadeOut: 0},
	{TiledBackground: 0},
	{Sprite3: 0},
	{Sine: 0},
	{Sprite4: 0},
	{decoration2: 0},
	{Decoration: 0},
	{Sine2: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{TiledBackground2: 0},
	{Text5: 0},
	{Sprite11: 0},
	{Text6: 0},
	{Text7: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Score: 0}
];

self.InstanceType = {
	Hand1: class extends self.ISpriteInstance {},
	Hand2: class extends self.ISpriteInstance {},
	gamBg: class extends self.ITiledBackgroundInstance {},
	Ball: class extends self.ISpriteInstance {},
	GameOver: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Solids: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Text2: class extends self.ITextInstance {},
	Text3: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Text4: class extends self.ITextInstance {},
	SCORET: class extends self.ITextInstance {},
	rtyBg: class extends self.ITiledBackgroundInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	retry: class extends self.ITextInstance {},
	Mouse: class extends self.IInstance {},
	FadeIn: class extends self.ISpriteInstance {},
	FadeOut: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	decoration2: class extends self.ISpriteInstance {},
	Decoration: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	Text5: class extends self.ITextInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Text6: class extends self.ITextInstance {},
	Text7: class extends self.ITextInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {}
}